### ISSUE TITLE
Rancher launcher is not idempotent

### ISSUE THREAD

**Issue by sonnysideup** [cerebrotech/terraform-aws-rancher#4]
The script will fail on subsequent runs if the SSH key has already been SCP'd onto the central server. This issue surfaced because of another bug here: https://github.com/cerebrotech/terraform-aws-rancher/blob/master/modules/ranchhand/main.tf#L41-L51. There is an extra dash after the interpolation.

**Comment by steved** [comment]
Moved to _ranchhand_.
